import java.util.ArrayList;
import java.util.HashMap;

import com.google.gson.internal.LinkedTreeMap;

 

public class workmain {
	public static void main(String[] args) {
	getpaths();
	getpathnodes();
	getprovelems();
	getprefnodes();
	loadpartpref();
		
		
	}

 
	private static void getpaths() {
		//call 1
		String nodeID="ebfd5885-8749-432e-96b1-b1178b4dffb6";
				//"7b91425e-c47f-44ca-abcf-2700c0bffb0f";
				//"01c731fe-c3f3-4f62-891e-db2ec29e7f44";
		//
		 String oux="curl -X POST -H \"Content-Type: application/json\" -d '{"
			 		+ "\"action\":\"getpaths\","
			 		+"\"nodeID\":"+nodeID+","
			 		+ "\"user\":\"Joe\","
			 		+ "\"obf\":false"
			 		+ "}"
			 		+ "' http://localhost:8080/provsimp/rest/ProcProv";
		 oux=oux.replaceAll("\n", "");
		System.out.println(oux);
		
		String paths=" [{\"hint\":\" Given the provenance chain, information http://www.itacispaces.org/Node7b91425e-c47f-44ca-abcf-2700c0bffb0f \n- was derived from Moira_Notif_7b91425e-c47f-44ca-abcf-2700c0bffb0f\n- was associated with A_Patrol\n- was generated by Reporting073\n- was generated at time 2014-08-28T02:14:50Z\nthe stated provenance elements infer information http://www.itacispaces.org/Node7b91425e-c47f-44ca-abcf-2700c0bffb0f\n=> Therefore, information http://www.itacispaces.org/Node7b91425e-c47f-44ca-abcf-2700c0bffb0f is credible\",\"pathid\":\"01b580be-9131-46ec-a1b6-5f8c16534ad9\",\"title\":\"P2 - Generation Pattern\"},{\"hint\":\" Given the provenance chain, information http://www.itacispaces.org/Node7b91425e-c47f-44ca-abcf-2700c0bffb0f \n- was derived from A_Patrol_Report\n- was associated with Moira\n- was generated by Aquiring073\n- was generated at time 2017-07-15T00:36:00Z\nthe stated provenance elements infer information http://www.itacispaces.org/Node7b91425e-c47f-44ca-abcf-2700c0bffb0f\n=> Therefore, information http://www.itacispaces.org/Node7b91425e-c47f-44ca-abcf-2700c0bffb0f is credible\",\"pathid\":\"6019a93a-1ebf-45b5-b133-6438f5937539\",\"title\":\"P1 - Generation Pattern\"},{\"hint\":\" Given the provenance chain, information http://www.itacispaces.org/Node7b91425e-c47f-44ca-abcf-2700c0bffb0f \n- was associated with Moira\n- was generated by Aquiring073\n- was generated by using primary sources A_Patrol_Report\nthe stated provenance elements infer information http://www.itacispaces.org/Node7b91425e-c47f-44ca-abcf-2700c0bffb0f\n=> Therefore, information http://www.itacispaces.org/Node7b91425e-c47f-44ca-abcf-2700c0bffb0f is credible\",\"pathid\":\"d14828b4-546f-4e9c-a6c7-c2c816c761f4\",\"title\":\"P3 - Primary Sources Pattern\"}]";
		
		
	}
	private static void getpathnodes() {
		//call 2
				String nodeID="ebfd5885-8749-432e-96b1-b1178b4dffb6";
					//	"7b91425e-c47f-44ca-abcf-2700c0bffb0f";
				String pathID="cc388379-68df-45c9-b095-5bdbf1c44065";
						//"bb2f4794-835e-4540-8004-b587712bc657";
				 String oux="curl -X POST -H \"Content-Type: application/json\" -d '{"
					 		+ "\"action\":\"getpathnodes\","
					 		+"\"nodeID\":"+nodeID+","
					 		+"\"pathID\":"+pathID+","
					 		+ "\"user\":\"Joe\""
					 		+ "}"
					 		+ "' http://localhost:8080/provsimp/rest/ProcProv";
				 oux=oux.replaceAll("\n", "");
				System.out.println(oux);
		
	}
	private static void getprovelems() {
		// call 1 p
		 
		 String nodes="[{\"text\":\"Pro\",\"dtg\":\"2016/08/14 18:28:00\",\"annot\":{\"id\":\"N/A\"},\"nodeID\":\"ebfd1111-8749-432e-96b1-b1178b4dffb6\",\"source\":\"Joe\",\"type\":\"RA\"},{\"source\":\"Joe\",\"uncert\":\"Confirmed\",\"eval\":\"V\",\"text\":\"Mark said she does not own a phone\",\"input\":\"INFO\",\"dtg\":\"2016/08/14 18:27:40\",\"commit\":\"N/A\",\"type\":\"I\",\"nodeID\":\"ebfd5885-8749-432e-96b1-b1178b4dffb6\",\"annot\":{\"conc\":{},\"prem_assump\":{}}},{\"source\":\"Joe\",\"uncert\":\"Confirmed\",\"eval\":\"V\",\"text\":\"Mark said she does not own a phone\",\"input\":\"INFO\",\"dtg\":\"2016/08/14 18:27:40\",\"commit\":\"N/A\",\"type\":\"I\",\"nodeID\":\"7305115e-ba09-4683-a5c1-4c30d7b4746f\",\"annot\":{\"conc\":{},\"prem_assump\":{}}},{\"source\":\"Joe\",\"uncert\":\"Confirmed\",\"eval\":\"V\",\"text\":\"Susan liked Billy’s blog page posted during the weekend\",\"input\":\"INFO\",\"dtg\":\"2016/07/20 09:27:23\",\"commit\":\"N/A\",\"type\":\"I\",\"nodeID\":\"7b91425e-c47f-44ca-abcf-2700c0bffb0f\",\"annot\":{\"conc\":{},\"prem_assump\":{}}},{\"source\":\"Joe\",\"uncert\":\"Confirmed\",\"eval\":\"V\",\"text\":\"Susan can only access internet at home\",\"input\":\"INFO\",\"dtg\":\"2016/07/20 09:45:30\",\"commit\":\"N/A\",\"type\":\"I\",\"nodeID\":\"ac7cc9f1-a29b-4e10-b4b4-94b2a93c7a1c\",\"annot\":{\"conc\":{},\"prem_assump\":{}}},{\"text\":\"Con\",\"dtg\":\"2016/07/20 09:27:54\",\"annot\":{\"cq_ans_node_id\":null,\"as_pro_node_uuid\":null,\"cq_id\":null},\"nodeID\":\"16f822c2-9b2b-436a-af3f-17b36212f05f\",\"source\":\"Joe\",\"type\":\"CA\"},{\"text\":\"Con\",\"dtg\":\"2016/07/20 09:27:56\",\"annot\":{\"cq_ans_node_id\":null,\"as_pro_node_uuid\":null,\"cq_id\":null},\"nodeID\":\"08b6fb7f-6363-4d64-b9ba-06824cecefc0\",\"source\":\"Joe\",\"type\":\"CA\"},{\"source\":\"Joe\",\"uncert\":\"Confirmed\",\"eval\":\"V\",\"text\":\"Susan may not own a phone\",\"input\":\"CLAIM\",\"dtg\":\"2016/07/20 09:27:25\",\"commit\":\"N/A\",\"type\":\"I\",\"nodeID\":\"01c731fe-c3f3-4f62-891e-db2ec29e7f44\",\"annot\":{\"conc\":{},\"prem_assump\":{}}},{\"text\":\"Pro\",\"dtg\":\"2016/07/20 09:27:32\",\"annot\":{\"id\":\"N/A\"},\"nodeID\":\"e310be5c-f47c-4390-a265-d272a694bf3d\",\"source\":\"Joe\",\"type\":\"RA\"}]";
			
		 String oux="curl -X POST -H \"Content-Type: application/json\" -d '{"
			 		+ "\"action\":\"getprovelems\","
			 		+"\"nodes\":"+nodes+","
			 		+ "\"user\":\"Joe\","
			 		+ "\"obf\": false"
			 		+ "}"
			 		+ "' http://localhost:8080/provsimp/rest/ProcProv";
		 oux=oux.replaceAll("\n", "");
		System.out.println(oux);
	}
	private static void getprefnodes() {
		//call 2 p
	 String nodes="[{\"input\":\"CLAIM\",\"eval\":\"N/A\",\"dtg\":\"2017/07/15 15:17:11\",\"commit\":\"N/A\",\"text\":\"*There is a person named John Doe and is in Kish.* is a credible information\",\"source\":\"Prov_Analysis_Node_7b91425e-c47f-44ca-abcf-2700c0bffb0f\",\"type\":\"I\",\"annot\":{\"conc\":{},\"prem_assump\":{\"0a559152-861d-4473-ab82-20eda3d9995b\":{\"cqs\":[],\"assump\":[],\"id\":\"LPV\",\"prem\":[\"PPV1\"]}}},\"nodeID\":\"77f31f47-d67c-42c8-a9ee-1ecab002c2c4\",\"uncert\":\"Confirmed\"},{\"input\":\"CLAIM\",\"eval\":\"N/A\",\"dtg\":\"2017/07/15 15:17:11\",\"commit\":\"N/A\",\"text\":\"Info \n- was associated with Moira\n- was generated by Aquiring444\n- was generated by using primary sources A_Patrol_Report\",\"source\":\"Prov_Analysis_Node_7b91425e-c47f-44ca-abcf-2700c0bffb0f\",\"type\":\"I\",\"annot\":{\"conc\":{},\"prem_assump\":{\"0a559152-861d-4473-ab82-20eda3d9995b\":{\"cqs\":[],\"assump\":[],\"id\":\"LPV\",\"prem\":[\"PPV2\"]}}},\"nodeID\":\"cbbb47f6-1408-42e5-abb8-28cbafcf1889\",\"uncert\":\"Confirmed\"},{\"dtg\":\"2017/07/15 15:17:11\",\"text\":\"LPV\",\"source\":\"Prov_Analysis_Node_7b91425e-c47f-44ca-abcf-2700c0bffb0f\",\"type\":\"RA\",\"annot\":{\"id\":\"LPV\"},\"nodeID\":\"0a559152-861d-4473-ab82-20eda3d9995b\"},{\"text\":\"Pro\",\"dtg\":\"2016/08/14 18:28:00\",\"annot\":{\"id\":\"N/A\"},\"nodeID\":\"ebfd1111-8749-432e-96b1-b1178b4dffb6\",\"source\":\"Joe\",\"type\":\"RA\"},{\"source\":\"Joe\",\"uncert\":\"Confirmed\",\"eval\":\"V\",\"text\":\"Mark said she does not own a phone\",\"input\":\"INFO\",\"dtg\":\"2016/08/14 18:27:40\",\"commit\":\"N/A\",\"type\":\"I\",\"nodeID\":\"ebfd5885-8749-432e-96b1-b1178b4dffb6\",\"annot\":{\"conc\":{},\"prem_assump\":{}}},{\"source\":\"Joe\",\"uncert\":\"Confirmed\",\"eval\":\"V\",\"text\":\"Mark said she does not own a phone\",\"input\":\"INFO\",\"dtg\":\"2016/08/14 18:27:40\",\"commit\":\"N/A\",\"type\":\"I\",\"nodeID\":\"7305115e-ba09-4683-a5c1-4c30d7b4746f\",\"annot\":{\"conc\":{},\"prem_assump\":{}}},{\"source\":\"Joe\",\"uncert\":\"Confirmed\",\"eval\":\"V\",\"text\":\"Susan liked Billy’s blog page posted during the weekend\",\"input\":\"INFO\",\"dtg\":\"2016/07/20 09:27:23\",\"commit\":\"N/A\",\"type\":\"I\",\"nodeID\":\"7b91425e-c47f-44ca-abcf-2700c0bffb0f\",\"annot\":{\"conc\":{},\"prem_assump\":{}}},{\"source\":\"Joe\",\"uncert\":\"Confirmed\",\"eval\":\"V\",\"text\":\"Susan can only access internet at home\",\"input\":\"INFO\",\"dtg\":\"2016/07/20 09:45:30\",\"commit\":\"N/A\",\"type\":\"I\",\"nodeID\":\"ac7cc9f1-a29b-4e10-b4b4-94b2a93c7a1c\",\"annot\":{\"conc\":{},\"prem_assump\":{}}},{\"text\":\"Con\",\"dtg\":\"2016/07/20 09:27:54\",\"annot\":{\"cq_ans_node_id\":null,\"as_pro_node_uuid\":null,\"cq_id\":null},\"nodeID\":\"16f822c2-9b2b-436a-af3f-17b36212f05f\",\"source\":\"Joe\",\"type\":\"CA\"},{\"text\":\"Con\",\"dtg\":\"2016/07/20 09:27:56\",\"annot\":{\"cq_ans_node_id\":null,\"as_pro_node_uuid\":null,\"cq_id\":null},\"nodeID\":\"08b6fb7f-6363-4d64-b9ba-06824cecefc0\",\"source\":\"Joe\",\"type\":\"CA\"},{\"source\":\"Joe\",\"uncert\":\"Confirmed\",\"eval\":\"V\",\"text\":\"Susan may not own a phone\",\"input\":\"CLAIM\",\"dtg\":\"2016/07/20 09:27:25\",\"commit\":\"N/A\",\"type\":\"I\",\"nodeID\":\"01c731fe-c3f3-4f62-891e-db2ec29e7f44\",\"annot\":{\"conc\":{},\"prem_assump\":{}}},{\"text\":\"Pro\",\"dtg\":\"2016/07/20 09:27:32\",\"annot\":{\"id\":\"N/A\"},\"nodeID\":\"e310be5c-f47c-4390-a265-d272a694bf3d\",\"source\":\"Joe\",\"type\":\"RA\"},{\"input\":\"CLAIM\",\"eval\":\"N/A\",\"dtg\":\"2017/07/15 15:23:06\",\"commit\":\"N/A\",\"text\":\"*A Toxic Bacteria contaminated the local water system in Kish* is a credible information\",\"source\":\"Prov_Analysis_Node_ebfd5885-8749-432e-96b1-b1178b4dffb6\",\"type\":\"I\",\"annot\":{\"conc\":{},\"prem_assump\":{\"437fb6cc-5227-4784-b819-d9da5cc33963\":{\"cqs\":[],\"assump\":[],\"id\":\"LPV\",\"prem\":[\"PPV1\"]}}},\"nodeID\":\"f5dee81b-018d-4fa7-9552-672882b0c408\",\"uncert\":\"Confirmed\"},{\"input\":\"CLAIM\",\"eval\":\"N/A\",\"dtg\":\"2017/07/15 15:23:06\",\"commit\":\"N/A\",\"text\":\"Info \n- was derived from RI_83603dc6-44cd-43e1-8bc9-7a9d2b345742\n- was associated with CISpaces_HDC_Service, CISpaces_of_pippo\n- was generated by Process_CS_Res\n- was generated at time 2015-04-05T11:23:00Z\n- was generated by using Data_83603dc6-44cd-43e1-8bc9-7a9d2b345742, TASK_83603dc6-44cd-43e1-8bc9-7a9d2b345742\",\"source\":\"Prov_Analysis_Node_ebfd5885-8749-432e-96b1-b1178b4dffb6\",\"type\":\"I\",\"annot\":{\"conc\":{},\"prem_assump\":{\"437fb6cc-5227-4784-b819-d9da5cc33963\":{\"cqs\":[],\"assump\":[],\"id\":\"LPV\",\"prem\":[\"PPV2\"]}}},\"nodeID\":\"6b52834b-f484-450a-b51d-56e1f373761a\",\"uncert\":\"Confirmed\"},{\"dtg\":\"2017/07/15 15:23:06\",\"text\":\"LPV\",\"source\":\"Prov_Analysis_Node_ebfd5885-8749-432e-96b1-b1178b4dffb6\",\"type\":\"RA\",\"annot\":{\"id\":\"LPV\"},\"nodeID\":\"437fb6cc-5227-4784-b819-d9da5cc33963\"}]";
	 	 
	 String edges=" [{\"toID\":\"0a559152-861d-4473-ab82-20eda3d9995b\",\"edgeID\":\"11898b23-739c-4d2e-8792-94b81fcb8cb9\",\"fromID\":\"77f31f47-d67c-42c8-a9ee-1ecab002c2c4\"},{\"toID\":\"0a559152-861d-4473-ab82-20eda3d9995b\",\"edgeID\":\"77a02a98-c8ff-407b-9877-65be745bc136\",\"fromID\":\"cbbb47f6-1408-42e5-abb8-28cbafcf1889\"},{\"toID\":\"7b91425e-c47f-44ca-abcf-2700c0bffb0f\",\"edgeID\":\"f1f6e100-0bdc-4117-a221-1c16c3f64b7d\",\"fromID\":\"0a559152-861d-4473-ab82-20eda3d9995b\"},{\"edgeID\":\"E1\",\"fromID\":\"ebfd5885-8749-432e-96b1-b1178b4dffb6\",\"toID\":\"ebfd1111-8749-432e-96b1-b1178b4dffb6\",\"formEdgeID\":null},{\"edgeID\":\"E2\",\"fromID\":\"ebfd1111-8749-432e-96b1-b1178b4dffb6\",\"toID\":\"7305115e-ba09-4683-a5c1-4c30d7b4746f\",\"formEdgeID\":null},{\"edgeID\":\"E3\",\"fromID\":\"7b91425e-c47f-44ca-abcf-2700c0bffb0f\",\"toID\":\"e310be5c-f47c-4390-a265-d272a694bf3d\",\"formEdgeID\":null},{\"edgeID\":\"E4\",\"fromID\":\"e310be5c-f47c-4390-a265-d272a694bf3d\",\"toID\":\"ac7cc9f1-a29b-4e10-b4b4-94b2a93c7a1c\",\"formEdgeID\":null},{\"edgeID\":\"E5\",\"fromID\":\"ebfd5885-8749-432e-96b1-b1178b4dffb6\",\"toID\":\"16f822c2-9b2b-436a-af3f-17b36212f05f\",\"formEdgeID\":null},{\"edgeID\":\"E6\",\"fromID\":\"16f822c2-9b2b-436a-af3f-17b36212f05f\",\"toID\":\"7b91425e-c47f-44ca-abcf-2700c0bffb0f\",\"formEdgeID\":null},{\"edgeID\":\"E7\",\"toID\":\"ebfd5885-8749-432e-96b1-b1178b4dffb6\",\"fromID\":\" 08b6fb7f-6363-4d64-b9ba-06824cecefc0\",\"formEdgeID\":null},{\"edgeID\":\"E8\",\"fromID\":\" 08b6fb7f-6363-4d64-b9ba-06824cecefc0\",\"toID\":\"7b91425e-c47f-44ca-abcf-2700c0bffb0f\",\"formEdgeID\":null},{\"toID\":\"437fb6cc-5227-4784-b819-d9da5cc33963\",\"edgeID\":\"0c57d2f5-f04a-4f03-b3df-ccea44933b78\",\"fromID\":\"f5dee81b-018d-4fa7-9552-672882b0c408\"},{\"toID\":\"437fb6cc-5227-4784-b819-d9da5cc33963\",\"edgeID\":\"94762055-e4f2-446c-b291-370b8553cf7d\",\"fromID\":\"6b52834b-f484-450a-b51d-56e1f373761a\"},{\"toID\":\"ebfd5885-8749-432e-96b1-b1178b4dffb6\",\"edgeID\":\"44f90b67-e211-4f74-9e5b-48de97cea5e2\",\"fromID\":\"437fb6cc-5227-4784-b819-d9da5cc33963\"}]";
	 String graph="{\"nodes\":"+nodes+",\"edges\":"+edges+"}";
	 String elems="[{\"cats\":[[\"Joe\",1.0],[\"Moira\",2.0],[\"A_Patrol\",1.0],[\"Patrol_M\",1.0],[\"pippo\",1.0],[\"CISpaces_HDC_Service\",1.0],[\"CISpaces_of_pippo\",2.0]],\"question\":\"Order of trustworthiness of actors\",\"qid\":\"0\"},{\"cats\":[[\"Process_CS_Res\",1.0],[\"CreateNodefd92a\",1.0],[\"HandOver_M\",1.0],[\"Collect_CS_Res\",1.0],[\"Reporting444\",1.0],[\"CreateNode6334f\",1.0],[\"Prepare_CS_Task\",1.0],[\"Create_CS_RI\",1.0],[\"Aquiring444\",1.0]],\"question\":\"Order of reliability of processes\",\"qid\":\"1\"},{\"cats\":[[\"Trustworthiness\",1.0],[\"Timeliness\",1.0],[\"Reliability\",2.0],[\"Accuracy\",1.0]],\"question\":\"Order of criteria\",\"qid\":\"2\"}]";
	 String oux="curl -X POST -H \"Content-Type: application/json\" -d '{"
		 		+ "\"action\":\"getprefnodes\","
		 		+"\"graph\":"+graph+","
		 		+"\"elements\":"+elems+","
		 		+ "\"user\":\"Joe\","
		 		+ "\"obf\": false"
		 		+ "}"
		 		+ "' http://localhost:8080/provsimp/rest/ProcProv";
	 oux=oux.replaceAll("\n", "");
	System.out.println(oux);
	}
	private static void loadpartpref() {
		 //CALL 3 P
		//this really needs the full interaction laid down before testing
	}

}
 