package provncontrol.pdatastr;

public class Pgoal implements Ppath{
 
	private String p1;
	private String p2;
	private String a;
	private String goal;
	private String time;
 
	private int tid;
	private String arg;
	private String core;
	private String title;
	private String hint;
	private String prem1;
	private String prem2;
 
	private String id;
	private String root;
 
 
	public Pgoal(String id, String p1,String p2, String a, String goal, String root,int t) {
		this.p1=p1;
		this.p2=p2;
		this.id=id;
		this.a=a;
		this.goal=goal;
		this.root=root;
		this.tid=t;
	}

	 
	public String getRoot() {
		return root;
	}
	public String getArg() {
		return arg;
	}
 
	public String getId() {
		return id;
	}
	public String getCore() {
		return core;
	}
	public String getTitle() {
		return title;
	}
	public String getHint() {
		return hint;
	}
 
	public String getPrem1() {
		return prem1;
	}
	public String getPrem2() {
		return prem2;
	}
	
	
	
	
	public String getP1() {
		return p1;
	}
	public void setP1(String p1) {
		this.p1 = p1;
	}
	public String getP2() {
		return p2;
	}
	public void setP2(String p2) {
		this.p2 = p2;
	}
	public String getA() {
		return a;
	}
	public void setA(String a) {
		this.a = a;
	}
	public String getGoal() {
		return goal;
	}
	public void setGoal(String goal) {
		this.goal = goal;
	}
	public String getTime() {
		return time;
	}
	public void setTime(String time) {
		this.time = time;
	}

	public int getTid() {
		return tid;
	}
	public void setTid(int tid) {
		this.tid = tid;
	}
	public void setForExport(){
		title="P"+tid+" - Goal Pattern";
		hint=goal;
		core="";
		String arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8;
		arg1=" Given the provenance chain, information "+root+" ";
		LabelConstructor lcon=new LabelConstructor();
		String process1=lcon.getLabActivityRules(p1);
			arg4="\n- was generated by "+process1+"";
			core=core+arg4;
			String process2=lcon.getLabActivityRules(p2);
			arg2="\n- was informed by "+process2+"";
			core=core+arg2;
			if(time!=null){
				arg5="\n- was generated at time "+time+"";
				core=core+arg5;
			}
			arg3="\n- was generated to satisfy goal "+goal+"";
			core=core+arg3;
			arg6="\n- was generated by using "+a+"";
			core=core+arg6;
		 
		
			arg7="the stated provenance elements infer information "+root+"";
			arg8="=> Therefore, information "+root+" is credible";
			
			arg=arg1+core+"\n"+arg7+"\n"+arg8;
		//	core=core.replaceAll("\\r\\n|\\r|\\n", " ");
			prem1=""+root+" is a credible information";
			prem2="Info "+core;
			 
			
		//	System.out.println("\n\n"+hint+"\n"+title+"\n"+arg+"\n\n"+prem1+"\n"+prem2);
	 
	}
	 
}

 

 