package provncontrol.pdatastr;

import java.util.HashSet;

public class Pps implements Ppath{
	private int tid;
 
	private String p;
	private HashSet<String> entity;
	private HashSet<String> agent;
	private String arg;
	private String core;
	private String title;
	private String hint;
	private String prem1;
	private String prem2;
 
	private String id;
	private String root;
	
 
	
	public Pps(String p,String id, String root,int t) {
		this.p=p;
		entity=new HashSet();
		agent=new HashSet();
		this.id=id;
		this.root=root;
		this.tid=t;
	
	}
	

	 
	public String getRoot() {
		return root;
	}
	public String getArg() {
		return arg;
	}
 
	public String getId() {
		return id;
	}
	public String getCore() {
		return core;
	}
	public String getTitle() {
		return title;
	}
	public String getHint() {
		return hint;
	}
 
	public String getPrem1() {
		return prem1;
	}
	public String getPrem2() {
		return prem2;
	}
	
	public void addAgent(String agg){
		agent.add(agg);
	}
	public void addEntity(String entt){
		entity.add(entt);
	}

	public String getP() {
		return p;
	}

	public void setP(String p) {
		this.p = p;
	}

	public HashSet getEntity() {
		return entity;
	}

	public HashSet getAgent() {
		return agent;
	}
 

	public int getTid() {
		return tid;
	}

	public void setTid(int tid) {
		this.tid = tid;
	}
	 
	public void setForExport(){
		title="P"+tid+" - Primary Sources Pattern";
		hint="";
		core="";
		for(String ent:entity){
			hint+="-"+ent;
		}
		hint=hint.substring(1,hint.length());
		String arg1, arg3,arg4, arg6,arg7,arg8;
		LabelConstructor lcon=new LabelConstructor();
		arg1=" Given the provenance chain, information "+root+" ";
	 
			if(!agent.isEmpty()){
				arg3="";
				for(String item:agent){
					arg3+=","+item;
				}
				arg3=arg3.substring(1, arg3.length());
				arg3="\n- was associated with "+arg3+"";
				core=core+arg3;
			}
			String process=lcon.getLabActivityRules(p);
			arg4="\n- was generated by "+process+"";
			core=core+arg4;
			 
			if(!entity.isEmpty()){
				arg6="";
				for(String item:entity){
					arg6+=","+item;
				}
				arg6=arg6.substring(1, arg6.length());
				arg6="\n- was generated by using primary sources "+arg6+"";
				core=core+arg6;
			}
		
			arg7="the stated provenance elements infer information "+root+"";
			arg8="=> Therefore, information "+root+" is credible";
			
			arg=arg1+core+"\n"+arg7+"\n"+arg8;
		//	core=core.replaceAll("\\r\\n|\\r|\\n", " ");
			prem1=""+root+" is a credible information";
			prem2="Info "+core;
			 
			
			//System.out.println("\n\n"+hint+"\n"+title+"\n"+arg+"\n\n"+prem1+"\n"+prem2);
	 
	}
	

}



