CREATE TABLE GAIANDB.CISPACES_PATHS
(
    WBOXID varchar(255),
    NDID varchar(255) NOT NULL,
    PATHID varchar(255) NOT NULL,
    TITLE varchar(255),
    HINT varchar(255),
    ARG varchar(1000),
    PREM1 varchar(550),
    PREM2 varchar(500),
    USED smallint,
    CONSTRAINT CISPACES_PATHS_PK PRIMARY KEY (NDID, PATHID)
);
INSERT INTO GAIANDB.CISPACES_PATHS (WBOXID, NDID, PATHID, TITLE, HINT, ARG, PREM1, PREM2, USED) VALUES ('Miles', '2025d1ee-fb50-4bbb-8e76-e17c25e2902d', '939d61ca-2bc2-4215-907f-d493d00f4824', 'P1 - Generation Pattern', 'CreateNode0ef9ef9c-e1bd-460b-a31c-12c92e709f51', ' Given the provenance chain, information *Info* 
- was associated with Miles
- was generated by CreateNode0ef9e
- was generated at time 2017-06-22T02:28:48Z
the stated provenance elements infer information *Info*
=> Therefore, information *Info* is credible', '*Info* is a credible information', 'Info 
- was associated with Miles
- was generated by CreateNode0ef9e
- was generated at time 2017-06-22T02:28:48Z', 0);
INSERT INTO GAIANDB.CISPACES_PATHS (WBOXID, NDID, PATHID, TITLE, HINT, ARG, PREM1, PREM2, USED) VALUES ('Joe', '69f3c290-9071-45eb-bced-9104b3f48de9', 'a27e9d6d-4e0b-43df-9c9b-e92e325600fe', 'P1 - Generation Pattern', 'CreateNode7becb363-9913-46b2-9651-3dd61af2ced4', ' Given the provenance chain, information *Info* 
- was associated with Joe
- was generated by CreateNode7becb
- was generated at time 2017-06-23T03:26:20Z
the stated provenance elements infer information *Info*
=> Therefore, information *Info* is credible', '*Info* is a credible information', 'Info 
- was associated with Joe
- was generated by CreateNode7becb
- was generated at time 2017-06-23T03:26:20Z', 0);
INSERT INTO GAIANDB.CISPACES_PATHS (WBOXID, NDID, PATHID, TITLE, HINT, ARG, PREM1, PREM2, USED) VALUES ('Joe', '81990c96-14c4-4a09-8c53-118733effc10', '40e659ee-1527-42bf-b9e8-73f59babad4f', 'P1 - Generation Pattern', 'CreateNodeef5b57a3-232a-4f4f-911a-0fcf0d66ad42', ' Given the provenance chain, information *Claim* 
- was associated with Joe
- was generated by CreateNodeef5b5
- was generated at time 2017-06-23T03:27:05Z
the stated provenance elements infer information *Claim*
=> Therefore, information *Claim* is credible', '*Claim* is a credible information', 'Info 
- was associated with Joe
- was generated by CreateNodeef5b5
- was generated at time 2017-06-23T03:27:05Z', 1);
INSERT INTO GAIANDB.CISPACES_PATHS (WBOXID, NDID, PATHID, TITLE, HINT, ARG, PREM1, PREM2, USED) VALUES ('Joe', '66d225b6-c7c7-4544-915e-6a8db3a5c961', '597e8389-8a00-4592-9faa-f07855d03510', 'P1 - Generation Pattern', 'CreateNodeec65ee03-3917-4828-8489-17449584b006', ' Given the provenance chain, information *Info* 
- was associated with Joe
- was generated by CreateNodeec65e
- was generated at time 2017-06-26T02:49:10Z
the stated provenance elements infer information *Info*
=> Therefore, information *Info* is credible', '*Info* is a credible information', 'Info 
- was associated with Joe
- was generated by CreateNodeec65e
- was generated at time 2017-06-26T02:49:10Z', 0);
INSERT INTO GAIANDB.CISPACES_PATHS (WBOXID, NDID, PATHID, TITLE, HINT, ARG, PREM1, PREM2, USED) VALUES ('Joe', '649edf6c-2629-4eeb-bca7-efa0e73ec42d', 'af11b683-6068-425e-8da2-c49172758fc3', 'P1 - Generation Pattern', 'CreateNode0e5c64eb-874c-470d-b2b5-338c1ca26bb2', ' Given the provenance chain, information *Info* 
- was associated with Joe
- was generated by CreateNode0e5c6
- was generated at time 2017-07-03T10:08:56Z
the stated provenance elements infer information *Info*
=> Therefore, information *Info* is credible', '*Info* is a credible information', 'Info 
- was associated with Joe
- was generated by CreateNode0e5c6
- was generated at time 2017-07-03T10:08:56Z', 1);
INSERT INTO GAIANDB.CISPACES_PATHS (WBOXID, NDID, PATHID, TITLE, HINT, ARG, PREM1, PREM2, USED) VALUES ('Joe', '183185e9-1a10-4794-8812-f808fa5e78bb', 'c9dd66c1-6b6c-423d-a8e1-41cd7dca070e', 'P1 - Generation Pattern', 'CreateNodefb689fcc-be57-4f99-ace5-4aba6198171c', ' Given the provenance chain, information *Claim* 
- was associated with Joe
- was generated by CreateNodefb689
- was generated at time 2017-07-03T10:11:47Z
the stated provenance elements infer information *Claim*
=> Therefore, information *Claim* is credible', '*Claim* is a credible information', 'Info 
- was associated with Joe
- was generated by CreateNodefb689
- was generated at time 2017-07-03T10:11:47Z', 0);
INSERT INTO GAIANDB.CISPACES_PATHS (WBOXID, NDID, PATHID, TITLE, HINT, ARG, PREM1, PREM2, USED) VALUES ('Joe', 'ce7a8c5c-57e2-4750-80aa-1e08f5b06fdb', '65d177c0-5421-43da-bc08-5d894e532c0e', 'P1 - Generation Pattern', 'CreateNodea43aba82-d46c-4d6b-a0f1-4cee0a23f7db', ' Given the provenance chain, information *Claim* 
- was associated with Joe
- was generated by CreateNodea43ab
- was generated at time 2017-07-03T03:17:56Z
the stated provenance elements infer information *Claim*
=> Therefore, information *Claim* is credible', '*Claim* is a credible information', 'Info 
- was associated with Joe
- was generated by CreateNodea43ab
- was generated at time 2017-07-03T03:17:56Z', 1);
INSERT INTO GAIANDB.CISPACES_PATHS (WBOXID, NDID, PATHID, TITLE, HINT, ARG, PREM1, PREM2, USED) VALUES ('Joe', '872e03ca-dc62-43d5-8451-581152f713a1', '63bcd26b-bc7b-43a3-bb12-22a41663274a', 'P1 - Generation Pattern', 'CreateNode8be6da2d-1d2d-49e8-bf77-874ec598e8d0', ' Given the provenance chain, information *Claim* 
- was associated with Joe
- was generated by CreateNode8be6d
- was generated at time 2017-07-03T04:02:19Z
the stated provenance elements infer information *Claim*
=> Therefore, information *Claim* is credible', '*Claim* is a credible information', 'Info 
- was associated with Joe
- was generated by CreateNode8be6d
- was generated at time 2017-07-03T04:02:19Z', 0);
INSERT INTO GAIANDB.CISPACES_PATHS (WBOXID, NDID, PATHID, TITLE, HINT, ARG, PREM1, PREM2, USED) VALUES ('Ella', '073aca90-b506-4d2f-bc77-7cf966a10e0f', '603525cf-c985-4977-ac13-ab4b17178c06', 'P1 - Generation Pattern', 'CreateNode80ae8690-26de-4aea-b201-09012fdd4652', ' Given the provenance chain, information *Info* 
- was associated with Ella
- was generated by CreateNode80ae8
- was generated at time 2017-07-04T10:52:10Z
the stated provenance elements infer information *Info*
=> Therefore, information *Info* is credible', '*Info* is a credible information', 'Info 
- was associated with Ella
- was generated by CreateNode80ae8
- was generated at time 2017-07-04T10:52:10Z', 1);
INSERT INTO GAIANDB.CISPACES_PATHS (WBOXID, NDID, PATHID, TITLE, HINT, ARG, PREM1, PREM2, USED) VALUES ('Ella', 'd988bb7f-200a-4e59-9ccd-6fdb6b901b76', '27560e6d-c4a6-4b35-9a55-c08ba27b9166', 'P1 - Generation Pattern', 'CreateNode55860c6f-88a0-47c3-b1fe-802c1a6cc0cf', ' Given the provenance chain, information *Claim* 
- was associated with Ella
- was generated by CreateNode55860
- was generated at time 2017-07-04T10:52:11Z
the stated provenance elements infer information *Claim*
=> Therefore, information *Claim* is credible', '*Claim* is a credible information', 'Info 
- was associated with Ella
- was generated by CreateNode55860
- was generated at time 2017-07-04T10:52:11Z', 0);
INSERT INTO GAIANDB.CISPACES_PATHS (WBOXID, NDID, PATHID, TITLE, HINT, ARG, PREM1, PREM2, USED) VALUES ('Ella', 'ffebea19-e42a-41a1-a215-bb8acd1aebd2', 'ff400832-081f-4f00-90b1-269c4e242fd3', 'P1 - Generation Pattern', 'GenerateNGOReport', ' Given the provenance chain, information *Toxic Bacteria contaminated the local water system in Kish* 
- was derived from NGO_Water_Cont_Report
- was associated with NGOChemicalLab
- was generated by GenerateNGOReport
- was generated at time 2014-09-07T08:46:41Z
- was generated by using NGOReportformat
the stated provenance elements infer information *Toxic Bacteria contaminated the local water system in Kish*
=> Therefore, information *Toxic Bacteria contaminated the local water system in Kish* is credible', '*Toxic Bacteria contaminated the local water system in Kish* is a credible information', 'Info 
- was derived from NGO_Water_Cont_Report
- was associated with NGOChemicalLab
- was generated by GenerateNGOReport
- was generated at time 2014-09-07T08:46:41Z
- was generated by using NGOReportformat', 0);
INSERT INTO GAIANDB.CISPACES_PATHS (WBOXID, NDID, PATHID, TITLE, HINT, ARG, PREM1, PREM2, USED) VALUES ('Ella', 'ffebea19-e42a-41a1-a215-bb8acd1aebd2', 'ce7fb027-a2c5-42de-b0fd-cfb7d2d03776', 'P3 - Generation Pattern', 'CollectWaterData', ' Given the provenance chain, information *Toxic Bacteria contaminated the local water system in Kish* 
- was associated with WaterSensor
- was generated by CollectWaterData
- was generated at time 2014-09-04T08:46:41Z
the stated provenance elements infer information *Toxic Bacteria contaminated the local water system in Kish*
=> Therefore, information *Toxic Bacteria contaminated the local water system in Kish* is credible', '*Toxic Bacteria contaminated the local water system in Kish* is a credible information', 'Info 
- was associated with WaterSensor
- was generated by CollectWaterData
- was generated at time 2014-09-04T08:46:41Z', 0);
INSERT INTO GAIANDB.CISPACES_PATHS (WBOXID, NDID, PATHID, TITLE, HINT, ARG, PREM1, PREM2, USED) VALUES ('Ella', 'ffebea19-e42a-41a1-a215-bb8acd1aebd2', 'e41958ac-7e1b-44da-9f9c-f73f29c32857', 'P5 - Goal Pattern', 'MonitoringWaterSupply', ' Given the provenance chain, information *Toxic Bacteria contaminated the local water system in Kish* 
- was generated by LabWaterTesting
- was informed by GenerateReq
- was generated at time 2014-08-30T08:46:41Z
- was generated to satisfy goal MonitoringWaterSupply
- was generated by using MonitorWaterRequirements
the stated provenance elements infer information *Toxic Bacteria contaminated the local water system in Kish*
=> Therefore, information *Toxic Bacteria contaminated the local water system in Kish* is credible', '*Toxic Bacteria contaminated the local water system in Kish* is a credible information', 'Info 
- was generated by LabWaterTesting
- was informed by GenerateReq
- was generated at time 2014-08-30T08:46:41Z
- was generated to satisfy goal MonitoringWaterSupply
- was generated by using MonitorWaterRequirements', 0);
INSERT INTO GAIANDB.CISPACES_PATHS (WBOXID, NDID, PATHID, TITLE, HINT, ARG, PREM1, PREM2, USED) VALUES ('Ella', 'ffebea19-e42a-41a1-a215-bb8acd1aebd2', '3f9ddfb9-e50c-4e7e-9b0c-689000b4facb', 'P2 - Generation Pattern', 'LabWaterTesting', ' Given the provenance chain, information *Toxic Bacteria contaminated the local water system in Kish* 
- was associated with NGOLabAssistant
- was generated by LabWaterTesting
- was generated at time 2014-09-06T08:46:41Z
- was generated by using WaterSampleData, MonitorWaterRequirements
the stated provenance elements infer information *Toxic Bacteria contaminated the local water system in Kish*
=> Therefore, information *Toxic Bacteria contaminated the local water system in Kish* is credible', '*Toxic Bacteria contaminated the local water system in Kish* is a credible information', 'Info 
- was associated with NGOLabAssistant
- was generated by LabWaterTesting
- was generated at time 2014-09-06T08:46:41Z
- was generated by using WaterSampleData, MonitorWaterRequirements', 0);
INSERT INTO GAIANDB.CISPACES_PATHS (WBOXID, NDID, PATHID, TITLE, HINT, ARG, PREM1, PREM2, USED) VALUES ('Ella', 'ffebea19-e42a-41a1-a215-bb8acd1aebd2', 'e248564a-1dd9-42fe-a289-1d6046da86a6', 'P4 - Primary Sources Pattern', 'WaterSampleData', ' Given the provenance chain, information *Toxic Bacteria contaminated the local water system in Kish* 
- was associated with NGOLabAssistant
- was generated by LabWaterTesting
- was generated by using primary sources WaterSampleData
the stated provenance elements infer information *Toxic Bacteria contaminated the local water system in Kish*
=> Therefore, information *Toxic Bacteria contaminated the local water system in Kish* is credible', '*Toxic Bacteria contaminated the local water system in Kish* is a credible information', 'Info 
- was associated with NGOLabAssistant
- was generated by LabWaterTesting
- was generated by using primary sources WaterSampleData', 0);
INSERT INTO GAIANDB.CISPACES_PATHS (WBOXID, NDID, PATHID, TITLE, HINT, ARG, PREM1, PREM2, USED) VALUES ('Ella', '2cde27df-9675-4d16-9bcc-c1c194a4669e', '876ad052-a2f7-4f5a-9b8c-81cd072ce2f1', 'P1 - Generation Pattern', 'CreateNode969dcecc-9b5f-40b3-8615-f2aa4101f81c', ' Given the provenance chain, information *Fall-out from the explosion affected a large area* 
- was associated with Miles
- was generated by CreateNode969dc
- was generated at time 2015-12-17T05:30:15Z
the stated provenance elements infer information *Fall-out from the explosion affected a large area*
=> Therefore, information *Fall-out from the explosion affected a large area* is credible', '*Fall-out from the explosion affected a large area* is a credible information', 'Info 
- was associated with Miles
- was generated by CreateNode969dc
- was generated at time 2015-12-17T05:30:15Z', 1);
INSERT INTO GAIANDB.CISPACES_PATHS (WBOXID, NDID, PATHID, TITLE, HINT, ARG, PREM1, PREM2, USED) VALUES ('Joe', 'ffebea19-e42a-41a1-a215-bb8acd1aebd2', 'c6fb3542-5317-4dfb-8ea0-83b4ce6e6b00', 'P1 - Generation Pattern', 'CreateNode615a7eb2-30e3-48e6-b712-057c2f13a34f', ' Given the provenance chain, information *Toxic Bacteria contaminated the local water system in Kish* 
- was associated with NGO_Water_Cont_Report
- was generated by CreateNode615a7
- was generated at time 2014-09-07T09:46:41Z
the stated provenance elements infer information *Toxic Bacteria contaminated the local water system in Kish*
=> Therefore, information *Toxic Bacteria contaminated the local water system in Kish* is credible', '*Toxic Bacteria contaminated the local water system in Kish* is a credible information', 'Info 
- was associated with NGO_Water_Cont_Report
- was generated by CreateNode615a7
- was generated at time 2014-09-07T09:46:41Z', 0);
INSERT INTO GAIANDB.CISPACES_PATHS (WBOXID, NDID, PATHID, TITLE, HINT, ARG, PREM1, PREM2, USED) VALUES ('Joe', '139a6d45-9576-4066-9907-134f2c429f0b', '05614af7-1595-42db-a70d-5e2900da6253', 'P1 - Generation Pattern', 'CreateNode8caf5b1c-ad67-4c0d-8156-8b18f26e2324', ' Given the provenance chain, information *There are bacteria in the water supply* 
- was associated with Joe
- was generated by CreateNode8caf5
- was generated at time 2014-09-07T08:56:37Z
the stated provenance elements infer information *There are bacteria in the water supply*
=> Therefore, information *There are bacteria in the water supply* is credible', '*There are bacteria in the water supply* is a credible information', 'Info 
- was associated with Joe
- was generated by CreateNode8caf5
- was generated at time 2014-09-07T08:56:37Z', 0);
INSERT INTO GAIANDB.CISPACES_PATHS (WBOXID, NDID, PATHID, TITLE, HINT, ARG, PREM1, PREM2, USED) VALUES ('Joe', 'fcab8cb9-5b31-4ebf-a202-80d9821746b3', '465ffe82-4d78-4221-adf1-05bc2e868785', 'P1 - Generation Pattern', 'CreateNode02c47065-997d-49e0-af24-eccc1acb1bed', ' Given the provenance chain, information *Non-waterborne bacteria were engineered and released in the water supply* 
- was associated with Joe
- was generated by CreateNode02c47
- was generated at time 2014-09-07T08:56:56Z
the stated provenance elements infer information *Non-waterborne bacteria were engineered and released in the water supply*
=> Therefore, information *Non-waterborne bacteria were engineered and released in the water supply* is credible', '*Non-waterborne bacteria were engineered and released in the water supply* is a credible information', 'Info 
- was associated with Joe
- was generated by CreateNode02c47
- was generated at time 2014-09-07T08:56:56Z', 0);
INSERT INTO GAIANDB.CISPACES_PATHS (WBOXID, NDID, PATHID, TITLE, HINT, ARG, PREM1, PREM2, USED) VALUES ('Joe', '417097cc-b0d0-43d5-9c10-cc2e04ca9bcd', 'f5e3f5e3-a12e-4a81-a37b-5e38ef5124b2', 'P1 - Generation Pattern', 'CreateNodeda886cb2-1c2d-4116-907c-0e4af8ce74aa', ' Given the provenance chain, information *NON-waterborne bacteria contaminate the water supply* 
- was associated with Joe
- was generated by CreateNodeda886
- was generated at time 2014-09-07T08:56:53Z
the stated provenance elements infer information *NON-waterborne bacteria contaminate the water supply*
=> Therefore, information *NON-waterborne bacteria contaminate the water supply* is credible', '*NON-waterborne bacteria contaminate the water supply* is a credible information', 'Info 
- was associated with Joe
- was generated by CreateNodeda886
- was generated at time 2014-09-07T08:56:53Z', 0);
INSERT INTO GAIANDB.CISPACES_PATHS (WBOXID, NDID, PATHID, TITLE, HINT, ARG, PREM1, PREM2, USED) VALUES ('Joe', '85ac9943-f3e3-4d93-a306-ea514dc8a9b2', '17919ee0-166f-4ace-8b2c-a91233bde9c6', 'P1 - Generation Pattern', 'CreateNode79d2aabe-ea09-4191-b69a-665e8cace45d', ' Given the provenance chain, information *Claim* 
- was associated with Joe
- was generated by CreateNode79d2a
- was generated at time 2017-07-17T08:57:59Z
the stated provenance elements infer information *Claim*
=> Therefore, information *Claim* is credible', '*Claim* is a credible information', 'Info 
- was associated with Joe
- was generated by CreateNode79d2a
- was generated at time 2017-07-17T08:57:59Z', 0);
INSERT INTO GAIANDB.CISPACES_PATHS (WBOXID, NDID, PATHID, TITLE, HINT, ARG, PREM1, PREM2, USED) VALUES ('Joe', '46071d1c-1209-4fce-a7c3-6a8f7fd0e154', '04a7e268-c6bb-4b2a-845b-5d6ad9987d55', 'P1 - Generation Pattern', 'CreateNode23aa3e91-80be-4e38-8050-0f2053ac94ba', ' Given the provenance chain, information *Info* 
- was associated with Joe
- was generated by CreateNode23aa3
- was generated at time 2017-07-17T08:57:58Z
the stated provenance elements infer information *Info*
=> Therefore, information *Info* is credible', '*Info* is a credible information', 'Info 
- was associated with Joe
- was generated by CreateNode23aa3
- was generated at time 2017-07-17T08:57:58Z', 1);
INSERT INTO GAIANDB.CISPACES_PATHS (WBOXID, NDID, PATHID, TITLE, HINT, ARG, PREM1, PREM2, USED) VALUES ('Joe', '4e83ad0f-3533-42ac-94d3-ad4d7bab015c', 'a185e501-1ab1-4658-9706-2d9d75d729f8', 'P1 - Generation Pattern', 'CreateNodefff4d41c-596f-4ab4-98c6-e2a38b775e3b', ' Given the provenance chain, information *Waterborne bacteria contaminate the water supply* 
- was associated with Joe
- was generated by CreateNodefff4d
- was generated at time 2014-09-07T08:56:44Z
the stated provenance elements infer information *Waterborne bacteria contaminate the water supply*
=> Therefore, information *Waterborne bacteria contaminate the water supply* is credible', '*Waterborne bacteria contaminate the water supply* is a credible information', 'Info 
- was associated with Joe
- was generated by CreateNodefff4d
- was generated at time 2014-09-07T08:56:44Z', 0);
INSERT INTO GAIANDB.CISPACES_PATHS (WBOXID, NDID, PATHID, TITLE, HINT, ARG, PREM1, PREM2, USED) VALUES ('Abc', 'e64d1637-831b-4772-aa5a-3fe88457fea6', '14d3fae5-951a-43aa-8ff1-8476086b7427', 'P1 - Generation Pattern', 'CreateNode2b250b67-5c9c-4d23-8368-98d1a93958b4', ' Given the provenance chain, information *Info* 
- was associated with Ella
- was generated by CreateNode2b250
- was generated at time 2017-08-02T03:22:28Z
the stated provenance elements infer information *Info*
=> Therefore, information *Info* is credible', '*Info* is a credible information', 'Info 
- was associated with Ella
- was generated by CreateNode2b250
- was generated at time 2017-08-02T03:22:28Z', 0);
INSERT INTO GAIANDB.CISPACES_PATHS (WBOXID, NDID, PATHID, TITLE, HINT, ARG, PREM1, PREM2, USED) VALUES ('Ella', '1634dd3b-8a92-4c3b-bbd3-ea5de9622af7', '980ddcdd-51da-44b5-bbda-1f47476a8f7e', 'P1 - Generation Pattern', 'CreateNode7be41c0a-ec28-4b2c-9d57-8799f64abb73', ' Given the provenance chain, information *Claim* 
- was associated with Ella
- was generated by CreateNode7be41
- was generated at time 2017-08-02T03:29:46Z
the stated provenance elements infer information *Claim*
=> Therefore, information *Claim* is credible', '*Claim* is a credible information', 'Info 
- was associated with Ella
- was generated by CreateNode7be41
- was generated at time 2017-08-02T03:29:46Z', 0);
INSERT INTO GAIANDB.CISPACES_PATHS (WBOXID, NDID, PATHID, TITLE, HINT, ARG, PREM1, PREM2, USED) VALUES ('Ella', '723add9b-a3e7-470e-bf64-0e4798906bbc', '71e01303-eafc-40e5-9c50-eb7db1c1131e', 'P1 - Generation Pattern', 'CreateNode40928100-8219-47c3-82b7-a4b576f6e2aa', ' Given the provenance chain, information *Claim* 
- was associated with Ella
- was generated by CreateNode40928
- was generated at time 2017-08-03T01:03:43Z
the stated provenance elements infer information *Claim*
=> Therefore, information *Claim* is credible', '*Claim* is a credible information', 'Info 
- was associated with Ella
- was generated by CreateNode40928
- was generated at time 2017-08-03T01:03:43Z', 0);
INSERT INTO GAIANDB.CISPACES_PATHS (WBOXID, NDID, PATHID, TITLE, HINT, ARG, PREM1, PREM2, USED) VALUES ('Joe', '855eca9e-0c61-433b-bf64-cb8bb6f912e4', '01263c26-437c-4693-90f9-3055870c09a0', 'P1 - Generation Pattern', 'CreateNode0dac5bcd-8374-4862-8cea-ee392c21e56a', ' Given the provenance chain, information *Traces of a similar substance were discovered at the border between Kish and Vast* 
- was associated with Kish_head_police_officer
- was generated by CreateNode0dac5
- was generated at time 2016-03-10T05:07:48Z
the stated provenance elements infer information *Traces of a similar substance were discovered at the border between Kish and Vast*
=> Therefore, information *Traces of a similar substance were discovered at the border between Kish and Vast* is credible', '*Traces of a similar substance were discovered at the border between Kish and Vast* is a credible information', 'Info 
- was associated with Kish_head_police_officer
- was generated by CreateNode0dac5
- was generated at time 2016-03-10T05:07:48Z', 0);
INSERT INTO GAIANDB.CISPACES_PATHS (WBOXID, NDID, PATHID, TITLE, HINT, ARG, PREM1, PREM2, USED) VALUES ('Joe', '04f73250-a377-4d75-a69a-c4a1cfaa6291', 'bfcd6969-5e57-4aa0-80ce-e248fe870493', 'P1 - Generation Pattern', 'CreateNode1cd81abe-b4e6-4553-8aa8-77b3853a24b8', ' Given the provenance chain, information *Protesters in Kish started riots in Purple Street* 
- was associated with Kish_Today_Newspaper
- was generated by CreateNode1cd81
- was generated at time 2016-03-06T11:13:38Z
the stated provenance elements infer information *Protesters in Kish started riots in Purple Street*
=> Therefore, information *Protesters in Kish started riots in Purple Street* is credible', '*Protesters in Kish started riots in Purple Street* is a credible information', 'Info 
- was associated with Kish_Today_Newspaper
- was generated by CreateNode1cd81
- was generated at time 2016-03-06T11:13:38Z', 0);
INSERT INTO GAIANDB.CISPACES_PATHS (WBOXID, NDID, PATHID, TITLE, HINT, ARG, PREM1, PREM2, USED) VALUES ('Joe', '2b7c387b-8964-4b82-b417-a65baec4671b', 'b7353f26-b059-4312-a2e3-e9b3ab359574', 'P1 - Generation Pattern', 'CreateNode12d02e60-0efe-4b8b-bf90-d6daa09c3606', ' Given the provenance chain, information *There is an exception to the causal rule that impedes the effect to occur* 
- was associated with Miles
- was generated by CreateNode12d02
- was generated at time 2016-03-10T06:25:00Z
the stated provenance elements infer information *There is an exception to the causal rule that impedes the effect to occur*
=> Therefore, information *There is an exception to the causal rule that impedes the effect to occur* is credible', '*There is an exception to the causal rule that impedes the effect to occur* is a credible information', 'Info 
- was associated with Miles
- was generated by CreateNode12d02
- was generated at time 2016-03-10T06:25:00Z', 0);