CREATE TABLE GAIANDB.CISPACES_PEXIST
(
    WBOXID varchar(255) NOT NULL,
    ARG varchar(1000) NOT NULL,
    CONSTRAINT CISPACES_PEXIST_PK PRIMARY KEY (WBOXID, ARG)
);
INSERT INTO GAIANDB.CISPACES_PEXIST (WBOXID, ARG) VALUES ('Joe', 'Info 
- was associated with Amnesty_International
- was generated by CreateNodeb0a3e
- was generated at time 2016-02-05T08:56:42Z');
INSERT INTO GAIANDB.CISPACES_PEXIST (WBOXID, ARG) VALUES ('Joe', 'Info 
- was associated with Quish_police
- was generated by CreateNodeb0483
- was generated at time 2016-02-05T09:34:15Z');
INSERT INTO GAIANDB.CISPACES_PEXIST (WBOXID, ARG) VALUES ('Joe', 'Info 
- was generated by Water_Bacteria_Investigation
- was informed by Aerial_Bacteria_Investigation
- was generated at time 2014-09-06T07:56:40Z
- was generated to satisfy goal Aerial_Bact_Study
- was generated by using Bacteria_Data_Request');